### ISSUE TITLE
Sponsor tools to cover

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [starlightknown/LearnScape#7]
- [x] Datree (@kaiwalyakoparkar )
- [ ] ~~Teleport (@kaiwalyakoparkar ) (As time permits not sure)~~
    - [ ]  ~~https://goteleport.com/docs/database-access/guides/mongodb-atlas/~~
- [x] .xyz domain (@shreemaan-abhishek )
- [x] Twillio api (SMS/ whatsapp) (@shreemaan-abhishek )
- [x] Google dev library (usage of angular or firebase? https://devlibrary.withgoogle.com/ submit here too if used) (@ashwinexe)
- [x] Stream (build an activity feed? ) (@starlightknown )
    - [x] https://getstream.io/chat/docs/sdk/react/ 
- [x] Allan ai (@starlightknown )
- [ ] ~~kubeshop (@kaiwalyakoparkar ) (As time permits not sure)~~
- [x] EddieHub (@kaiwalyakoparkar, @ashwinexe , @starlightknown , @shreemaan-abhishek )
- [x] GitHub (@kaiwalyakoparkar, @ashwinexe , @starlightknown , @shreemaan-abhishek )
- [ ] ~~Symbl.ai (@starlightknown )~~

**Comment by ashwinexe** [comment]
Google dev library is done using Firebase hosting
